import { Clover } from 'lucide-react'

/** 幸运卡：没有 +/- 和预设，只有掷骰按钮（重制设计 v2 §6-步骤1-③）。 */
export function LuckCard({
  value,
  luckRoll,
  rolling,
  error,
  autoGenerated,
  onRoll,
}: {
  value: number | null
  luckRoll: { kind: string; dice: number[] } | null
  rolling: boolean
  error: string
  autoGenerated: boolean
  onRoll: () => void
}) {
  return (
    <div className="bg-input border border-border-light rounded-[6px] px-3.5 py-3">
      <div className="flex items-center justify-between mb-2">
        <div className="text-[13px] font-semibold text-text-primary flex items-center gap-1.5">
          <Clover className="w-3.5 h-3.5 text-[#4a8a4a]" /> 幸运 LUCK
        </div>
        {value != null && luckRoll && (
          <span className="text-[10px] text-text-dim font-mono">
            {luckRoll.kind} [{luckRoll.dice.join(',')}]
          </span>
        )}
      </div>
      <div className="text-center text-[26px] font-bold font-mono text-text-primary mb-2">{value ?? '—'}</div>
      {value != null ? (
        <p className="text-[11px] text-text-dim text-center py-2">
          {autoGenerated ? '已由服务端掷骰生成' : '已掷幸运，不提供重掷'}
        </p>
      ) : (
        <button
          onClick={onRoll}
          disabled={rolling}
          className="w-full py-2 rounded-sm text-[12px] font-semibold bg-brass text-white active:bg-brass-dark transition-all disabled:opacity-60"
        >
          {rolling ? '掷骰中…' : '掷幸运（3d6×5）'}
        </button>
      )}
      {error && <p className="text-[11px] text-[#c04040] mt-1.5">{error}</p>}
      <p className="text-[10px] text-text-dim mt-2">
        幸运单独掷，不占上面的点数。若角色 15–19 岁，第 3 步会按规则重掷两次取高。
      </p>
    </div>
  )
}
