import { Clover } from 'lucide-react'

/** 幸运卡：没有 +/- 和预设，只有掷骰按钮（重制设计 v2 §6-步骤1-③）。 */
export function LuckCard({
  value,
  luckRoll,
  rolling,
  error,
  autoGenerated,
  onRoll,
}: {
  value: number | null
  luckRoll: { kind: string; dice: number[] } | null
  rolling: boolean
  error: string
  autoGenerated: boolean
  onRoll: () => void
}) {
  return (
    <div>
      <div className="flex items-center justify-between mb-1">
        <div className="text-[11.5px] font-semibold text-ink flex items-center gap-1.5">
          <Clover className="w-3.5 h-3.5 text-[#3d6b2f]" /> 幸运 LUCK
        </div>
        {value != null && luckRoll && (
          <span className="text-[10.5px] text-ink-soft font-mono">
            {luckRoll.kind} [{luckRoll.dice.join(',')}]
          </span>
        )}
      </div>
      <div className="text-center text-[26px] font-bold font-mono text-ink">{value ?? '—'}</div>
      {value != null ? (
        <p className="text-[10.5px] text-ink-soft text-center py-1">
          {autoGenerated ? '已由服务端掷骰生成' : '已掷幸运，不提供重掷'}
        </p>
      ) : (
        <button
          onClick={onRoll}
          disabled={rolling}
          className="cut-corner w-full py-2 mt-1 text-[12px] font-semibold bg-brass-dark text-dossier active:translate-y-[1px] transition-all disabled:opacity-60"
        >
          {rolling ? '掷骰中…' : '掷幸运（3d6×5）'}
        </button>
      )}
      {error && <p className="text-[10.5px] text-rust-dark mt-1.5">{error}</p>}
      <p className="text-[10.5px] text-ink-soft mt-2 leading-relaxed">
        幸运单独掷，不占上面的点数。若角色 15–19 岁，第 3 步会按规则重掷两次取高。
      </p>
    </div>
  )
}
