"""add character attribute_pool_total and background_detail

Revision ID: 47dc5dac094f
Revises: c288fe8f2cdd
Create Date: 2026-07-28 20:51:05.171550

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "47dc5dac094f"
down_revision: str | Sequence[str] | None = "c288fe8f2cdd"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # 两列都可空、不给 server_default：迁移之前建的卡走的都是 pointbuy/roll，
    # attribute_pool_total 只有 roll_pool 这条新路径会写；background_detail
    # 是结构化背景故事的补充字段，旧卡没填过，留 NULL 即可，不需要伪造默认值。
    op.add_column("characters", sa.Column("attribute_pool_total", sa.Integer(), nullable=True))
    op.add_column("characters", sa.Column("background_detail", sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("characters", "background_detail")
    op.drop_column("characters", "attribute_pool_total")
    # ### end Alembic commands ###
