"""add characters allocated_attributes

Revision ID: cf102dc39e5f
Revises: 47dc5dac094f
Create Date: 2026-07-29 18:31:45.136582

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "cf102dc39e5f"
down_revision: str | Sequence[str] | None = "47dc5dac094f"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("characters", sa.Column("allocated_attributes", sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("characters", "allocated_attributes")
    # ### end Alembic commands ###
