"""add character basic info fields

Revision ID: d6ed190ffc39
Revises: d5ad9a9ee34b
Create Date: 2026-07-20 21:25:32.976717

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "d6ed190ffc39"
down_revision: str | Sequence[str] | None = "d5ad9a9ee34b"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("characters", sa.Column("age", sa.Integer(), nullable=True))
    op.add_column("characters", sa.Column("gender", sa.String(length=20), nullable=True))
    op.add_column("characters", sa.Column("residence", sa.String(length=100), nullable=True))
    op.add_column("characters", sa.Column("birthplace", sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("characters", "birthplace")
    op.drop_column("characters", "residence")
    op.drop_column("characters", "gender")
    op.drop_column("characters", "age")
    # ### end Alembic commands ###
