"""pending checks to db

Revision ID: de3225b1cd99
Revises: 9c67731c71e7
Create Date: 2026-08-01 14:32:55.953282

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "de3225b1cd99"
down_revision: str | Sequence[str] | None = "9c67731c71e7"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "pending_checks",
        sa.Column("seq", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("check_request_id", sa.String(length=64), nullable=False),
        sa.Column("room_id", sa.Uuid(as_uuid=False), nullable=False),
        sa.Column("kind", sa.String(length=20), nullable=False),
        sa.Column("player_id", sa.Uuid(as_uuid=False), nullable=False),
        sa.Column("player_nickname", sa.String(length=100), nullable=False),
        sa.Column("skill", sa.String(length=100), nullable=True),
        sa.Column("loss_on_success", sa.String(length=20), nullable=False),
        sa.Column("loss_on_failure", sa.String(length=20), nullable=False),
        sa.Column("reason", sa.String(length=500), nullable=False),
        sa.Column("reveals", sa.JSON(), nullable=False),
        sa.Column("opposed_opponent", sa.String(length=100), nullable=True),
        sa.Column("opposed_value", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["player_id"],
            ["players.id"],
        ),
        sa.ForeignKeyConstraint(
            ["room_id"],
            ["rooms.id"],
        ),
        sa.PrimaryKeyConstraint("seq"),
    )
    op.create_index(
        op.f("ix_pending_checks_check_request_id"),
        "pending_checks",
        ["check_request_id"],
        unique=True,
    )
    op.create_index(op.f("ix_pending_checks_room_id"), "pending_checks", ["room_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_pending_checks_room_id"), table_name="pending_checks")
    op.drop_index(op.f("ix_pending_checks_check_request_id"), table_name="pending_checks")
    op.drop_table("pending_checks")
    # ### end Alembic commands ###
