"""room_sessions 加 recap_text

Revision ID: efd9a28a5c1b
Revises: b7d3f10c5a92
Create Date: 2026-08-24 11:16:09.068712

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "efd9a28a5c1b"
down_revision: str | Sequence[str] | None = "b7d3f10c5a92"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("room_sessions", sa.Column("recap_text", sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("room_sessions", "recap_text")
    # ### end Alembic commands ###
