"""导入报告加线索账本那两个数

Revision ID: f03b7f547b4f
Revises: efd9a28a5c1b
Create Date: 2026-08-25 15:24:56.085863

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f03b7f547b4f"
down_revision: str | Sequence[str] | None = "efd9a28a5c1b"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("module_import_jobs", sa.Column("fact_count", sa.Integer(), nullable=True))
    op.add_column(
        "module_import_jobs", sa.Column("revealing_check_count", sa.Integer(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("module_import_jobs", "revealing_check_count")
    op.drop_column("module_import_jobs", "fact_count")
    # ### end Alembic commands ###
